version: 0.1
phases:
  install:
    commands:
      - apt-get install zip -y
  post_build:
    commands:
      - zip templates.zip ./templates/* 
      - aws s3 cp --recursive --acl public-read ./templates s3://cnishant-cfn-test/templates.zip
