version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y zip
  post_build:
    commands:
      - zip templates.zip ./templates/* 
      - aws s3 cp --recursive --acl public-read ./templates.zip s3://cnishant-cfn-test/templates.zip
